### ISSUE TITLE
Add JWK support to importKey.

### ISSUE THREAD

**Issue by dajiaji** [dajiaji/hpke-js#133]

**Comment by OR13** [comment]
You are welcome to take anything you like from: https://github.com/transmute-industries/jose-hpke/blob/main/src/hpke.ts

You might also want to review:

- https://github.com/panva/jose/blob/main/src/key/generate_key_pair.ts
- https://github.com/panva/jose/blob/main/src/runtime/node/key_to_jwk.ts

**Comment by dajiaji** [comment]
Thanks for your infromation and using this lib!
I'm very interested in jose-hpke and its use cases!

Additionally, if you propose JOSE-HPKE as a standard, I will fully support it! Although my support might be a bother for you...

**Comment by OR13** [comment]
I'm not bothered by strong opinions.

Never apologize for having them :)
