### ISSUE TITLE
Support public key encoding and decoding at the suite 

### ISSUE THREAD

**Issue by chris-wood** [dajiaji/hpke-js#150]
It's sometimes necessary to encode and decode KEM public keys for transmission over the wire. There seems to be an API for doing this on the `KemInterface`, but I don't see an obvious way to invoke that. If it's not already done, would it make sense to expose these APIs for use?

**Comment by dajiaji** [comment]
Hi @chris-wood,

Actually, only in case for DHKEM(P-*), you can convert between raw keys and CryptoKeys in the following way.

```js
const suite = new CipherSuite({
    kem: Kem.DhkemP256HkdfSha256,
    kdf: Kdf.HkdfSha256,
    aead: Aead.Aes128Gcm
});

const rkp = await suite.generateKeyPair();

// CryptoKey to raw
const raw = await crypto.subtle.exportKey("raw", rkp.publicKey);

// raw to CryptoKey
const kemCtx = await suite.kemContext();
const cryptoKey = await kemCtx.importKey("raw", raw, true);
```

This method is not available in DHKEM(X*), so it might be better to have a utility function, for example, KemInterface.exportKey("raw", xxx).

KemInterface.exportKey() so that the upper application layer does not have to worry about Web Crypto API compatibility.

Is this what you want?

**Comment by chris-wood** [comment]
My understand of the raw representation of CryptoKey objects is that they are not equivalent to the HPKE public key serialized representation. If that's the case, then yes, something like the exportKey function you propose for KEMs would work well!

**Comment by dajiaji** [comment]
> My understand of the raw representation of CryptoKey objects is that they are not equivalent to the HPKE public key serialized representation.

I guess in some cases they will be the same, in other cases they will be different. Understood. At least, we might have to avoid the function name like `exportKey` which misleads that it's the same as Web Crypto API. Anyway, I'll implement it.

I'll ask you to review the PR. Wait for a few days.

**Comment by chris-wood** [comment]
Perfect -- thanks!

**Comment by dajiaji** [comment]
... I'm very sorry. I was going to implement it, but I had already done it 2 months ago.
... I completely forgot about it.

Could you update hpke-js to v0.18.2 and try it?

```
const suite = new CipherSuite({
    kem: Kem.DhkemP256HkdfSha256,
    kdf: Kdf.HkdfSha256,
    aead: Aead.Aes128Gcm
});
const kemContext = await suite.kemContext();
const kp = await kemContext.generateKeyPair();
// CryptoKey to raw
const rawPubKey = await kemContext.serializePublicKey(kp.publicKey);
// raw to CryptoKey
const pubKey = await kemContext.deserializePublicKey(rawPubKey);
```

If you want `serializePrivateKey()/deserializePrivateKey()` as well, feel free to ask me.

**Comment by chris-wood** [comment]
Encoding the public key is sufficient for now -- thank you! This works perfectly.
