### ISSUE TITLE
Plan for X25519 and Chacha20poly1305 implementation?

### ISSUE THREAD

**Issue by kdenhartog** [dajiaji/hpke-js#17]
Great work so far on this implementation! What's your plan for X25519 KEM and Chacha20poly1305 encryption since support seems to be spotty in browser for these algorithms?

I'm looking to use this implementation to play around with Oblivious DNS over HTTPS, but the[ implementation I'm trying to interoperate with ](https://github.com/cloudflare/odoh-rs) only supports the following crypto primitives `(KEM: X25519HkdfSha256, KDF: HkdfSha256, AEAD: AesGcm128)`. Should I plan on these cryptographic primitives being limited to only certain JS environments or do you have an idea in mind of how to get them supported in every major environment (particularly concerned about browser env right now)?

**Comment by dajiaji** [comment]
Thank you for considering the use of this library!

Yes, I intend to support X25519/X448. However, at this time I will only support the Node.js environment. If you are planning to use the X25519/X448 only on the Node.js environment, I can change my development plan and prioritize the development of the X25519/X448.

As you probably know, the W3C Web Cryptography API standard does not support the Edwards curves. However, there seems to be a plan to support it ([WICG: Secure Curves in the Web Cryptography API](https://wicg.github.io/webcrypto-secure-curves/)), so my original plan was to support X25519/X448 after the support in browsers has progressed.

In addition, I had planned to wait for Web Cryptography API support for ChaCha20/Poly1305 as well.

... however, if the need arises, I may consider supporting all of the HPKE cipher suites using like WASM-enabled primitive cipher implementations. I will consider this after quality improvement of the current implementations and CI environment development for continuous security updates.

**Comment by dajiaji** [comment]
> Would you be open to using a library like https://github.com/StableLib/stablelib/ when in a browser environment and using those primitives?

No problem. I didn't know about stablelib but it looks good, it could be an alternative until the Web Cryptography API supports them. Pull requests are welcome!

**Comment by kdenhartog** [comment]
Ok sounds good - I'll go ahead and resolve this one for now and when I get around to wanting to switch over to the X25519 implementation I'll follow back up with a PR/issue to get that going. Thanks for the great work on this library and I'm really looking forward to using it!

**Comment by dajiaji** [comment]
@kdenhartog FYI:  Kem:X25519HkdfSha256 and Aead:ChaCha20Poly1305 have been supported.
