### ISSUE TITLE
Question about the JS module size

### ISSUE THREAD

**Issue by Zhiyi-Zhang** [dajiaji/hpke-js#221]
We have been using hpke-js in our library. We found the hpke-js library is big in size.
Do you have some numbers for the size of the JS module?

<img width="465" alt="image" src="https://github.com/dajiaji/hpke-js/assets/10349944/0862ee2b-6d4a-4a7f-9f00-2fff16ca37a4">

**Comment by Zhiyi-Zhang** [comment]
The large size can also be caused by some of our internal tools that didn't successfully compress/optimize the JS files so I want to get some insights from you.

**Comment by dajiaji** [comment]
I think one of the issues is the use of external libraries to support ciphersuites that are not covered by the Web Cryptography API. Currently, I'm refactoring the code to use only the Web Cryptography API and create a core module that is independent of external dependencies. Additionally, we are separating the cryptographic suites that rely on external libraries into extension modules outside the core.

If you do not use x25519/x448 or chacha20, you only need to use @hpke/core, which significantly reduces the size. Please refer to the following for more information.

- https://bundlephobia.com/package/hpke-js@0.18.5
- https://bundlephobia.com/package/@hpke/core@0.22.2

There may be other issues with package generation as well. The npm package's support for esm/cjs dual compatibility could be affecting something. I'll also look into it on my end.
