### ISSUE TITLE
Consider adding ML-KEM

### ISSUE THREAD

**Issue by OR13** [dajiaji/hpke-js#306]
I'm testing JOSE and COSE HPKE with https://github.com/paulmillr/noble-post-quantum

I have some code blocks that use hpke-js for the DHKems and then I have to implement ML-KEM separately.

I also think that implementations of HPKE might consider starting to use the term "kem-ct" instead of "enc", ML-KEM based hpke should probably yield { ct, kem-ct } instead of { ct, enc }... It will be easier to align consuming implementations if parameters returned are not kem specific.

Or at least it should be documented that kem-ct is enc.

**Comment by dajiaji** [comment]
It's been a while.

The ML-KEM support for [crystals-kyber-js](https://github.com/dajiaji/crystals-kyber-js), which is used under hpke-js, is almost complete. Someone involved with openpgp.js implemented [the patch](https://github.com/dajiaji/crystals-kyber-js/pull/34) for crystals-kyber-js. I've been busy with my main job over the past month or two and haven't been able to address this, but it seems that the ML-KEM support for hpke-js can be implemented relatively soon.

Please wait a bit longer.

**Comment by dajiaji** [comment]
Hi @OR13, as the first step in supporting ML-KEM, I have EXPERIMENTALLY implemented [X-Wing](https://datatracker.ietf.org/doc/draft-connolly-cfrg-xwing-kem/). You can try X-Wing on various JS runtimes including web browsers (See [@hpke/hybridkem-x-wing](https://github.com/dajiaji/hpke-js/tree/main/packages/hybridkem-x-wing)).

In the PR #450, I have added some explanation about using "enc" as "ct".

Just wanted to report that for now.

**Comment by OR13** [comment]
in JWK, I would expect the private key to also contain the public key, for example:

```
  const jwkPriv = {
    kty: "AKP",
    kid: "01",
    alg: "X-Wing",
   pub:
      "4iNrNajCSzmxCqEyOpapGaLO2IQAYzp7BxMXE_wUsrWxnPw9pfoaksSfJVE-D9MNaxYRyauWNdcIZyekt9IdNCROZpac8Vs7KnhTKfYbCWsnfqA3ODR5prVW3nIx_kt_qcmsJMBpmgAYpSU0AbrPqQXKgWVz5WotLgZ-m3KHUzuhOpN97bMfpEus7UB2mSNhADSuMeYZoXAkUZmzxcOYZIWf4bTJcXoHwwSVvfuYoKACzPVsEobO9QQd7ePETPFr9WLHRIUYAms9i5lAaAq9OKFXX9J7WNoGO_rDLDnDCGk3TAXBrrGJi2swPMaL5FU0buCvaZY2IkoUjKKuoQRjERxwn2m2nHDOhTh0ZpjExgqa7wAwx5JM7sQqXTaBb1RerhMpNGCzrLN-oOE9cOSqeGhto5ioOXwI6vloghE_5Pe61NpAsFAeHHU-_nMFPIcBToZhwzCZr-i-3kFKWxqifYOSs-Ex6acMEFWHgkDK0PQNX-PN-FI26tl-KpdEg2OygIyq_VFs0lBSxcNiVDwlF-Ss0OYOwHFjAJtkJfwyJ3rO5xwkurU-2fKedMZqCjVklVmY12uWqai1DRY1pNemfrQt9WRNMwRXKTqAQvU8x6aSiPF-1Vgn6Cso6CZlqGoU-9lmReyoFywET4O8DYwLTIYmmFYxyoevgpBo8TWJY8szNmTKSCdjujs7sghXf5umrGLCX3ZZJ0O2S-UZMXcUy0ECy3svmiWytPBhXeMd7NnKVQJtbaC2URGxb-Uv7tikh-FERiptupNyj1ALb_xJ5RVWnvJf7Rev9SBQc2glNSWGD1i-O-YclkYEpqyBTmk1WWQCpSCkZws9KEMYhmWT0VpLsBw14-WH7gxn0ogNbyQH-3pwcSuDjeuWxde_K0S89gOMy-M_vPUaVKWE_pAIPJHHptQ9T7FfSMYML9ZuCoqtStZOXEK7iHfA6-wrXjh8ipiP3CO-ueFsh1d4HgoUmcYeE4wh8hbCnQdpeYccqmlCuvwJBUS-6ZtUsWy5qaNk1iRtn0LM5TxmtZxFyPmukpmnXRUYDDyVIVGpG3oQdyQp3Ey65vzGIvqAGMY0OfiQYwuZKNtrt_lDiuQGXtNNc9SG8_UvkPCAfciN_djHKOlU8aw1wGwADOQaBYJYDju1e2cpcokKxeeYjnhQZXEW8bV9CAmq7ewL7eGuFIFIMRxvfjFzRuUYn7jNY1uYb4wL3SdkHFhLd4s6kRqAvhyWkquOG7sSg5VzzOGd8YO0WDW7tVBS-fxmoWeO8qNt6nhBHmyNYFAbTmBZLRNpipQ7UJGF25EuLqEL4GFxI2syfHFxYJTJZKaLAzd_UToFvNmcHzRlg7sFKXehChKt_HWANOVhfaTBJ2WF5XdOHzuZeLCdDpxE07yGFRxDqtGFcScXNAIjrDgdIRUKBClOl7sTu9ohtaGCttqWnhmn_QcnN_qOiApTwkKOPQSbfSGXQFKW3bNhkSp7z0gnztYR0Men2hBN3kMiCVM59kph1bsQj_C_TXgMrlCfsiwlaRQZP_c0kEJYEjfVIoKIJO4739B_sD8flC0uoXn-ci8GzAPeW2mFntsG7_OJsn3OWYRFcCFiI1k9S6MtmrrIzQSQQO9lNA",
    priv: "f5wrpOiPgn1hYEVQdgWFPtc7gJP277yI6xpurPpm7yY",
    key_ops: ["deriveBits"],
  };
```

Other than this observation, and the potential algorithm name alignment, I don't have any more comments... this looks great to me.

**Comment by dajiaji** [comment]
@OR13 Thanks for your comment.

> In JWK, I would expect the private key to also contain the public key, for example:

Certainly, if we follow the OKP spec, we should include the public key ('pub') in the private key, but I was thinking it might be okay to omit 'pub' according to the AKP spec, so I inadvertently omitted it. 

But, at this point, it would probably be wise to include 'pub' as well. I’ll fix it.

**Comment by dajiaji** [comment]
I have experimentally implemented ML-KEM, so I will close this issue for now.

@OR13 As you are already aware, I have also experimentally supported key import with the AKP key type in JWK. Indeed, having a JWK definition improves usability in the web.
