### ISSUE TITLE
How to import public keys?

### ISSUE THREAD

**Issue by privy-scott** [dajiaji/hpke-js#337]
Consider the following snippet:

```typescript
import {CipherSuite, HkdfSha256, Aes256Gcm} from '@hpke/core';
import {DhkemX25519HkdfSha256} from '@hpke/dhkem-x25519';
import * as crypto from 'crypto';

(async () => {
const hpke = new CipherSuite({
  kem: new DhkemX25519HkdfSha256(),
  kdf: new HkdfSha256(),
  aead: new Aes256Gcm(),
});

const publicKey = await crypto.subtle.importKey(
    'jwk',
    {
      kty: 'OKP',
      crv: 'X25519',
      x: /* public key goes here */,
    },
    'X25519',
    true,
    [],
);

const sender = await hpke.createSenderContext({
  recipientPublicKey: publicKey,
});

})();
```

This fails unexpectedly:

> SerializeError: Cannot read properties of undefined (reading 'buffer')
>
>     at X25519.serializePublicKey (../../node_modules/@hpke/dhkem-x25519/script/src/kems/dhkemPrimitives/x25519.js:50:23)
>     at DhkemX25519HkdfSha256.encap (../../node_modules/@hpke/dhkem-x25519/script/src/kems/dhkem.js:121:26)
>     at CipherSuite.createSenderContext (../../node_modules/@hpke/core/script/src/cipherSuiteNative.js:196:24)

Is there a specific way we should be loading public keys from a string to use with this library?

**Comment by dajiaji** [comment]
@privy-scott Thank you for using the library.
Could you refer to the following test code? You should not need to use crypto.subtle.

https://github.com/dajiaji/hpke-js/blob/main/test/kemContext.test.ts#L818
