### ISSUE TITLE
NotSupportedError: Web Cryptograph API not supported

### ISSUE THREAD

**Issue by OR13** [dajiaji/hpke-js#95]
This happens when you try to run the examples in the readme directly with `jest`.

I tried creating `jest.config.js`, but it did not resolve the issue.

with:

```js
module.exports = {
  testEnvironment: 'node',
};
```

This is likely not a problem with your library, but rather with how `jest` handles node modules / es modules by default.

```
  "dependencies": {
    "hpke-js": "^0.13.0"
  },
  "devDependencies": {
    "jest": "^29.1.2"
  }
```

Work around... don't use jest.

**Comment by dajiaji** [comment]
I used to support jest but stopped supporting it when we started supporting Deno.

Could you try `testEnvironment: 'jsdom'` ?

**Comment by OR13** [comment]
I will give it a shot, thanks for the reply.

**Comment by Zhiyi-Zhang** [comment]
@OR13 
```
import crypto from 'crypto'
// ...
(self: any).crypto = (crypto: any).webcrypto;
```
solve the problem for me
