### ISSUE TITLE
Expose suite-specific KDF and AEAD interfaces

### ISSUE THREAD

**Issue by chris-wood** [dajiaji/hpke-js#96]
Some protocols that build on top of HPKE, such as [Oblivious HTTP](https://ietf-wg-ohai.github.io/oblivious-http/draft-ietf-ohai-ohttp.html), use the KDF and AEAD interfaces associated with a HPKE suite for various things. In the specific case of OHTTP, the KDF and AEAD interfaces are used to [encapsulate HTTP responses](https://ietf-wg-ohai.github.io/oblivious-http/draft-ietf-ohai-ohttp.html#name-encapsulation-of-responses) (pseudocode copied from the draft):

```
secret = context.Export("message/bhttp response", Nk)
response_nonce = random(max(Nn, Nk))
salt = concat(enc, response_nonce)
prk = Extract(salt, secret)
aead_key = Expand(prk, "key", Nk)
aead_nonce = Expand(prk, "nonce", Nn)
ct = Seal(aead_key, aead_nonce, "", response)
enc_response = concat(response_nonce, ct)
```

I don't see an obvious was to get access to these interfaces through the things that hpke-js exposes. One could certainly reimplement the KDF and AEAD interfaces on top of WebCrypto, but it seems a lot less error prone if this library allowed the caller to just use the already-implemented functions directly. 

@dajiaji, what do you think about exposing these? For context, I'm trying to implement a Javascript version of OHTTP, and this is the last bit that's required.

**Comment by dajiaji** [comment]
@chris-wood I had read the OHTTP draft some time ago and was just thinking about the need to expose the KDF and AEAD interfaces.

Please wait for a while. I think I can make time to update the library to expose KDF and AEAD interfaces by the end of this week.

**Comment by chris-wood** [comment]
Excellent -- thanks! I'm happy to offer reviews and be an early user if that helps, too.
